### PR TITLE
Dosen't work

### PR DESCRIPTION
**Pull request by Johnsonk79**
I just downloaded the plugin and this was shown in the console after I restart the server, the skywars command is there but there are no responses

[06:18:51] [Server thread/INFO]: Enabling SkyWarsForPE v3.0-BETA
[06:18:51] [Server thread/INFO]: [SkyWars] Starting SkyWarsForPE modules...
[06:18:51] [Server thread/INFO]: >> Invalid chests.yml: enchantment `14` in `level-2` doesn't appears to be exists.
[06:18:51] [Server thread/INFO]: [SkyWars] Loaded chest random configuration.
[06:18:51] [Server thread/INFO]: [SkyWars] Locating arena files...
[06:18:51] [Server thread/INFO]: [SkyWars] Beast World - Arena loaded and enabled
[06:18:51] [Server thread/CRITICAL]: RuntimeException: "Directory name must not be empty." (EXCEPTION) in "plugins/SkyWarsForPE_dev-45.phar/src/larryTheCoder/arena/Arena" at line 470
[06:18:51] [Server thread/DEBUG]: #0 plugins/SkyWarsForPE_dev-45.phar/src/larryTheCoder/arena/Arena(470): RecursiveDirectoryIterator->__construct(string[0] )
[06:18:51] [Server thread/DEBUG]: #1 plugins/SkyWarsForPE_dev-45.phar/src/larryTheCoder/arena/Arena(155): larryTheCoder\arena\Arena->saveArenaWorld()
[06:18:51] [Server thread/DEBUG]: #2 plugins/SkyWarsForPE_dev-45.phar/src/larryTheCoder/ArenaManager(69): larryTheCoder\arena\Arena->resetArena()
[06:18:51] [Server thread/DEBUG]: #3 plugins/SkyWarsForPE_dev-45.phar/src/larryTheCoder/SkyWarsPE(189): larryTheCoder\ArenaManager->checkArenas()
[06:18:51] [Server thread/DEBUG]: #4 src/pocketmine/plugin/PluginBase(123): larryTheCoder\SkyWarsPE->onEnable()
[06:18:51] [Server thread/DEBUG]: #5 src/pocketmine/plugin/PluginManager(581): pocketmine\plugin\PluginBase->setEnabled(boolean 1)

[06:18:51] [Server thread/DEBUG]: #6 src/pocketmine/Server(1999): pocketmine\plugin\PluginManager->enablePlugin(object larryTheCoder\SkyWarsPE)
[06:18:51] [Server thread/DEBUG]: #7 src/pocketmine/Server(1985): pocketmine\Server->enablePlugin(object larryTheCoder\SkyWarsPE)
[06:18:51] [Server thread/DEBUG]: #8 src/pocketmine/Server(1783): pocketmine\Server->enablePlugins(integer 1)
[06:18:51] [Server thread/DEBUG]: #9 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[15] /home/gs-41447/, string[23] /home/gs-41447/plugins/)
[06:18:51] [Server thread/DEBUG]: #10 src/pocketmine/PocketMine(295): pocketmine\server()
[06:18:51] [Server thread/DEBUG]: #11 (1): require(string[94] phar:///pro/bin/mcpe/pocketmine-stable-1.14.0/PocketMine-MP.phar/src/pocketmine/)
[06:18:51] [Server thread/INFO]: Disabling SkyWarsForPE v3.0-BETA
[06:18:51] [Server thread/INFO]: [SkyWars] SkyWarsForPE has disabled

### CODE REVIEW

**Comment by Johnsonk79** [comment]
thanks man!

**Comment by BogdanMakarchuk** [comment]
why did I delete the / stats / create commands and so on, how arenas configured now?

**Comment by Johnsonk79** [comment]
when will this be fixed?

**Comment by KingRainbow44** [comment]
[04:43:46] [Server thread/CRITICAL]: pocketmine\level\LevelException: "Invalid empty world name" (EXCEPTION) in "src/pocketmine/Server" at line 1086

Any information on this?

**Comment by larryTheCoder** [comment]
Hmm, welp, a fix soon will be patched after I get stuff done. It seems like the config that you're using is invalid or something, can't confirm.

**Pull request closed without merging**
