### PR TITLE
Not working

### PR DESCRIPTION
**Pull request by ElectroGamesYT**
First of all there isnt a Issue tab, SECOND do u got discord? i need help

### CODE REVIEW

**Comment by vasilishunter** [comment]
\TC73018520816563733706432\plugins\SkyWarsForPE-master\src\larryTheCoder\npc\FakeHuman.php on line 68" (EXCEPTION) in "src/pocketmine/entity/Skin" at line 62
npcs crash the plugin

**Comment by vasilishunter** [comment]
common players can run /sw start

**Comment by larryTheCoder** [comment]
Hmm, I will see what I could do on that. Also did u know that this plugin is still rewriting?

**Comment by vasilishunter** [comment]
thank you and no I didnt know that everthing else works too good to even think that its still been re-written

**Comment by vasilishunter** [comment]
Another problem that I notice is that players when players use /hub while in game they glitch out and that spectator mode doesn’t work but you probably already know that.

**Comment by vasilishunter** [comment]
one more thing can you also update the npcs to have the new 1.13 skin

**Comment by vasilishunter** [comment]
actually common players have perms to use all commands

**Comment by ElectroGamesYT** [comment]
How do I add kits? do i  need my own plugin like AdvancedKits?

**Comment by vasilishunter** [comment]
Yes you need a plugin that has the command /kit I recommend KitUI since you can access all the kits without having to run a secondary command and it’s easy to configure kits between ranks and worlds

**Comment by larryTheCoder** [comment]
Bruh, there is a lot of changes going on with pmmp, I will try to check @vasilishunter issue first.
There is no support for Kits nor any other kits plugins, I will also try to implement that in this month

**Comment by vasilishunter** [comment]
And about the Npcs crashing the server I was using a not official version of pocketmine now that the official has been released  the server still crashes but I think it’s because skins don’t work in the official version and I get a compound tag error  not from the plugin but pocketmine when I try to use npcs

**Comment by larryTheCoder** [comment]
@vasilishunter The NPC is not meant to be used since its implemented, and Im not sure why this PR still open but to clarify, this plugin is unstable and inconsistence. That is why Rewrite branch exists, to rewrite every inconsistency in this plugin. Hope you understand that master branch will not be updated until rewrite branch is finished.

**Comment by larryTheCoder** [comment]
Also my discord is MrPotato101#0060
See u there lol.

**Pull request merged**
