### PR TITLE
Help

### PR DESCRIPTION
**Pull request by 2cool4u567**
I crash sometimes and discord link is invalid so add me @ElectroGames#6784

### CODE REVIEW

**Comment by 2cool4u567** [comment]
Also the join sign isnt working

**Comment by 2cool4u567** [comment]
this plugin isnt working plz help

**Comment by larryTheCoder** [comment]
Hmm, changing the API and removing that will not gonna work.
I pushed a better version of this

**Comment by 2cool4u567** [comment]
whats ur discord name

**Pull request closed without merging**
